### ISSUE TITLE
Tab selection not visible (to me)

### ISSUE THREAD

**Issue by michael-wenyon** [davidschmitt/gnucash_gtk3#1]
Issue: When I have multiple tabs (accounts) open, there is no visual distinction of the tabs to show which account register is showing (selected). 

I see the account name written across the top of the window, but I would find a visual difference showing the selected tab more helpful. For example a different gray shade of background for the tab itself.
![Screenshot from 2021-08-09 13-31-35](https://user-images.githubusercontent.com/5072302/128749114-f78a7cba-9d9f-43c8-8221-6d3c243af4b9.png)

**Comment by davidschmitt** [comment]
Michael,

I've uploaded a more recent version of the stylesheet I use.  I believe it gives a small indicator of the tab selected using the right-border of the tab label.

Unfortunately, GnuCash implements stylesheets on widgets rather haphazardly.  So some things are impossible to adjust (like the lines separating splits within a single transaction).  After lots of effort (and frustration) I've reached the place where my stylesheet is "good enough" for me, so I don't plan to spend more time investigating it.

However, if you find a better setting to highlight the chosen tab, I'm happy to add it here.

**Comment by davidschmitt** [comment]
Hi again Michael,

I noticed the same highlight problem on other tabs (e.g. under Preferences dialog) and it bothered me enough to figure out how to highlight the "checked" tabs.  Changes have been committed to the master branch.

If you want stronger/other highlighting than just the brightened background, look for tab:checked in the css file and make your changes there.

-Dave

**Comment by michael-wenyon** [comment]
That works for me. Thank you!
