### ISSUE TITLE
Typo in filepath in README?

### ISSUE THREAD

**Issue by michael-wenyon** [davidschmitt/gnucash_gtk3#2]
I believe the 'example' of a specific location for the css file should be:

E.g. $HOME/.var/app/org.gnucash.GnuCash/config/gnucash/gtk-3.0.css

At this time, there is a '/' in the original given filepath which I think should be a '.'

Certainly, for me, in a Flatpak installation (on Debian 11 Bullseye), the file works in this location:

/home/michael/.var/app/org.gnucash.GnuCash/config/gnucash/gtk-3.0.css

It would be helpful to note this specific location pertains to a flatpak installation rather than one installed with a native package manager (although, at this time, Debian does not offer a recent Gnucash in its package).

**Comment by davidschmitt** [comment]
thanks for the feedback michael, I've updated the README with that correction
